/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package model.registry;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface Registry {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Registry\",\"namespace\":\"model.registry\",\"types\":[{\"type\":\"record\",\"name\":\"RegistryItem\",\"fields\":[{\"name\":\"address\",\"type\":\"string\"}]}],\"messages\":{\"register\":{\"request\":[{\"name\":\"message\",\"type\":\"RegistryItem\"}],\"response\":\"null\"},\"getAll\":{\"request\":[],\"response\":{\"type\":\"array\",\"items\":\"RegistryItem\"}},\"unregister\":{\"request\":[{\"name\":\"callerId\",\"type\":\"string\"}],\"response\":\"boolean\"},\"aliveCheck\":{\"request\":[{\"name\":\"registryId\",\"type\":\"string\"}],\"response\":\"boolean\"},\"getRest\":{\"request\":[{\"name\":\"registryId\",\"type\":\"string\"}],\"response\":{\"type\":\"array\",\"items\":\"RegistryItem\"}}}}");
  java.lang.Void register(model.registry.RegistryItem message) throws org.apache.avro.AvroRemoteException;
  java.util.List<model.registry.RegistryItem> getAll() throws org.apache.avro.AvroRemoteException;
  boolean unregister(java.lang.CharSequence callerId) throws org.apache.avro.AvroRemoteException;
  boolean aliveCheck(java.lang.CharSequence registryId) throws org.apache.avro.AvroRemoteException;
  java.util.List<model.registry.RegistryItem> getRest(java.lang.CharSequence registryId) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends Registry {
    public static final org.apache.avro.Protocol PROTOCOL = model.registry.Registry.PROTOCOL;
    void register(model.registry.RegistryItem message, org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
    void getAll(org.apache.avro.ipc.Callback<java.util.List<model.registry.RegistryItem>> callback) throws java.io.IOException;
    void unregister(java.lang.CharSequence callerId, org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
    void aliveCheck(java.lang.CharSequence registryId, org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
    void getRest(java.lang.CharSequence registryId, org.apache.avro.ipc.Callback<java.util.List<model.registry.RegistryItem>> callback) throws java.io.IOException;
  }
}