/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package model.registry;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class RegistryItem extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RegistryItem\",\"namespace\":\"model.registry\",\"fields\":[{\"name\":\"address\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence address;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public RegistryItem() {}

  /**
   * All-args constructor.
   */
  public RegistryItem(java.lang.CharSequence address) {
    this.address = address;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return address;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: address = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'address' field.
   */
  public java.lang.CharSequence getAddress() {
    return address;
  }

  /**
   * Sets the value of the 'address' field.
   * @param value the value to set.
   */
  public void setAddress(java.lang.CharSequence value) {
    this.address = value;
  }

  /** Creates a new RegistryItem RecordBuilder */
  public static model.registry.RegistryItem.Builder newBuilder() {
    return new model.registry.RegistryItem.Builder();
  }
  
  /** Creates a new RegistryItem RecordBuilder by copying an existing Builder */
  public static model.registry.RegistryItem.Builder newBuilder(model.registry.RegistryItem.Builder other) {
    return new model.registry.RegistryItem.Builder(other);
  }
  
  /** Creates a new RegistryItem RecordBuilder by copying an existing RegistryItem instance */
  public static model.registry.RegistryItem.Builder newBuilder(model.registry.RegistryItem other) {
    return new model.registry.RegistryItem.Builder(other);
  }
  
  /**
   * RecordBuilder for RegistryItem instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RegistryItem>
    implements org.apache.avro.data.RecordBuilder<RegistryItem> {

    private java.lang.CharSequence address;

    /** Creates a new Builder */
    private Builder() {
      super(model.registry.RegistryItem.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(model.registry.RegistryItem.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.address)) {
        this.address = data().deepCopy(fields()[0].schema(), other.address);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing RegistryItem instance */
    private Builder(model.registry.RegistryItem other) {
            super(model.registry.RegistryItem.SCHEMA$);
      if (isValidValue(fields()[0], other.address)) {
        this.address = data().deepCopy(fields()[0].schema(), other.address);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'address' field */
    public java.lang.CharSequence getAddress() {
      return address;
    }
    
    /** Sets the value of the 'address' field */
    public model.registry.RegistryItem.Builder setAddress(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.address = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'address' field has been set */
    public boolean hasAddress() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'address' field */
    public model.registry.RegistryItem.Builder clearAddress() {
      address = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public RegistryItem build() {
      try {
        RegistryItem record = new RegistryItem();
        record.address = fieldSetFlags()[0] ? this.address : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
