/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package model.wishlist;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Event { 
  ADD, REMOVE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Event\",\"namespace\":\"model.wishlist\",\"symbols\":[\"ADD\",\"REMOVE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
