/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package model.wishlist;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class WishListItem extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"WishListItem\",\"namespace\":\"model.wishlist\",\"fields\":[{\"name\":\"productId\",\"type\":\"string\"},{\"name\":\"client\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence productId;
  @Deprecated public java.lang.CharSequence client;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public WishListItem() {}

  /**
   * All-args constructor.
   */
  public WishListItem(java.lang.CharSequence productId, java.lang.CharSequence client) {
    this.productId = productId;
    this.client = client;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return productId;
    case 1: return client;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: productId = (java.lang.CharSequence)value$; break;
    case 1: client = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'productId' field.
   */
  public java.lang.CharSequence getProductId() {
    return productId;
  }

  /**
   * Sets the value of the 'productId' field.
   * @param value the value to set.
   */
  public void setProductId(java.lang.CharSequence value) {
    this.productId = value;
  }

  /**
   * Gets the value of the 'client' field.
   */
  public java.lang.CharSequence getClient() {
    return client;
  }

  /**
   * Sets the value of the 'client' field.
   * @param value the value to set.
   */
  public void setClient(java.lang.CharSequence value) {
    this.client = value;
  }

  /** Creates a new WishListItem RecordBuilder */
  public static model.wishlist.WishListItem.Builder newBuilder() {
    return new model.wishlist.WishListItem.Builder();
  }
  
  /** Creates a new WishListItem RecordBuilder by copying an existing Builder */
  public static model.wishlist.WishListItem.Builder newBuilder(model.wishlist.WishListItem.Builder other) {
    return new model.wishlist.WishListItem.Builder(other);
  }
  
  /** Creates a new WishListItem RecordBuilder by copying an existing WishListItem instance */
  public static model.wishlist.WishListItem.Builder newBuilder(model.wishlist.WishListItem other) {
    return new model.wishlist.WishListItem.Builder(other);
  }
  
  /**
   * RecordBuilder for WishListItem instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<WishListItem>
    implements org.apache.avro.data.RecordBuilder<WishListItem> {

    private java.lang.CharSequence productId;
    private java.lang.CharSequence client;

    /** Creates a new Builder */
    private Builder() {
      super(model.wishlist.WishListItem.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(model.wishlist.WishListItem.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.productId)) {
        this.productId = data().deepCopy(fields()[0].schema(), other.productId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.client)) {
        this.client = data().deepCopy(fields()[1].schema(), other.client);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing WishListItem instance */
    private Builder(model.wishlist.WishListItem other) {
            super(model.wishlist.WishListItem.SCHEMA$);
      if (isValidValue(fields()[0], other.productId)) {
        this.productId = data().deepCopy(fields()[0].schema(), other.productId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.client)) {
        this.client = data().deepCopy(fields()[1].schema(), other.client);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'productId' field */
    public java.lang.CharSequence getProductId() {
      return productId;
    }
    
    /** Sets the value of the 'productId' field */
    public model.wishlist.WishListItem.Builder setProductId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.productId = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'productId' field has been set */
    public boolean hasProductId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'productId' field */
    public model.wishlist.WishListItem.Builder clearProductId() {
      productId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'client' field */
    public java.lang.CharSequence getClient() {
      return client;
    }
    
    /** Sets the value of the 'client' field */
    public model.wishlist.WishListItem.Builder setClient(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.client = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'client' field has been set */
    public boolean hasClient() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'client' field */
    public model.wishlist.WishListItem.Builder clearClient() {
      client = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public WishListItem build() {
      try {
        WishListItem record = new WishListItem();
        record.productId = fieldSetFlags()[0] ? this.productId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.client = fieldSetFlags()[1] ? this.client : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
